### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by tjulises** [PsychoLlama/dotfiles#2]
Hello @PsychoLlama , 

I know that you have made this framework just for you haha
but I'd like to collaborate in it!!!
I'm a Graphic Designer, I'd like to provide a really cool logo 
for this really cool project!!! 
What do you think?
let me know, thanks!!!

**Comment by PsychoLlama** [comment]
Hey @tjulises! Thanks for your interest!
Although I love the idea, I think it would give the wrong impression. I make breaking changes in this project all the time, often with no explanation or warning. It gives me a great amount of flexibility and creative freedom.

For those reasons, I don't advertise the framework or generally recommend others use it. If it had a cool logo, it might confuse people into thinking the project is polished or ready for users (hopefully it will be someday!)

Much appreciated though! That's a really generous offer 🙇
